### ISSUE TITLE
Instructor Feedback Week 5 - Project Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [hhollister/my-cookbook#4]
- [ ] A note about issues/feedback. Please add an "X" to check off the checkboxes to indicate you have completed the work or responded to the questions. When all done, then you can close the issue. See example below:
- [x] A completed task.
- [ ] It may be a good idea to add your ddl here so that it's backed up.
- [x] Code? Where's the code? I'm looking for a Dao and related unit test for checkpoint 2. Be sure to add, commit, pull and push! 
- [ ] Something to keep in mind in general - if there were an error in the dao, what would the user experience be? You might consider throwing an exception (you can create your own exceptions) that the controller would catch and then route the user to a friendly-looking error page.
- [x] Consider saving your project screenshots as a pdf or image for easy viewing in GitHub.

**Comment by hhollister** [comment]
Sorry, forgot to add an add and just did a commit -am

**Comment by hhollister** [comment]
I will add ddl, just need a few changes. I will also keep the user experience noted in mind as well.
